name: .github/workflows/msvc.yml

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -S <relative-path-to-your-CMakeLists-directory> -B build
    - name: Build
      run: cmake --build build
